/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_HelloWorld */

#ifndef _Included_com_HelloWorld
#define _Included_com_HelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_HelloWorld
 * Method:    hello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_HelloWorld_hello
  (JNIEnv *, jobject);

/*
 * Class:     com_HelloWorld
 * Method:    setRecordValue
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_HelloWorld_setRecordValue
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_HelloWorld
 * Method:    getRecordValue
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_HelloWorld_getRecordValue
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
